### ISSUE TITLE
license expired

### ISSUE THREAD

**Issue by bastinald** [jjuback/gc-excelviewer#170]
keep getting popups saying license is wijmo license expired

**Comment by jjuback** [comment]
We are aware of the issue, and will post an update as soon as we can.

**Comment by jjuback** [comment]
Fixed in version 3.0.43.

**Comment by bersbersbers** [comment]
The issue is back, it seems:

![image](https://user-images.githubusercontent.com/12128514/157229515-ac87b5df-6af0-47a5-a32a-2bfe6305c88a.png)

**Comment by jjuback** [comment]
We are aware of the issue and will post an update as soon as we can.

**Comment by liaeh** [comment]
Hi, I encountered the same issue today with Excel Viewer v4.2.56
